class WordItem {
  final String word;
  final String meaning;
  final String emoji;
  WordItem(this.word, this.meaning, {required this.emoji});
}

final List<WordItem> easyWords = [
  WordItem('Apple', 'แอปเปิล', emoji: '🍎'),
  WordItem('Ball', 'ลูกบอล', emoji: '⚽'),
  WordItem('Cat', 'แมว', emoji: '🐱'),
  WordItem('Dog', 'สุนัข', emoji: '🐶'),
  WordItem('Egg', 'ไข่', emoji: '🥚'),
  WordItem('Fish', 'ปลา', emoji: '🐟'),
  WordItem('Goat', 'แพะ', emoji: '🐐'),
  WordItem('Hat', 'หมวก', emoji: '🎩'),
  WordItem('Ice', 'น้ำแข็ง', emoji: '🧊'),
  WordItem('Jam', 'แยม', emoji: '🫙🍓'),
  WordItem('Milk', 'นม', emoji: '🥛'),
  WordItem('House', 'บ้าน', emoji: '🏠'),
  WordItem('Chair', 'เก้าอี้', emoji: '🪑'),
  WordItem('Table', 'โต๊ะ', emoji: '🛋️'),
  WordItem('Pen', 'ปากกา', emoji: '🖊️'),
  WordItem('Bird', 'นก', emoji: '🐦'),
  WordItem('Rain', 'ฝน', emoji: '🌧️'),
  WordItem('School', 'โรงเรียน', emoji: '🏫'),
  WordItem('Phone', 'โทรศัพท์', emoji: '📱'),
  WordItem('Shoe', 'รองเท้า', emoji: '👟'),
  WordItem('Sun', 'พระอาทิตย์', emoji: '☀️'),
  WordItem('Moon', 'พระจันทร์', emoji: '🌙'),
  WordItem('Star', 'ดาว', emoji: '⭐'),
  WordItem('Tree', 'ต้นไม้', emoji: '🌳'),
  WordItem('Mom', 'แม่', emoji: '👩‍👧'),
  WordItem('Dad', 'พ่อ', emoji: '👨‍👧'),
  WordItem('Baby', 'ทารก', emoji: '👶'),
  WordItem('Toy', 'ของเล่น', emoji: '🧸'),
];

final List<WordItem> mediumWords = [
  WordItem('Beautiful', 'สวยงาม', emoji: '✨'),
  WordItem('Bottle', 'ขวด', emoji: '🍼'),
  WordItem('Camera', 'กล้อง', emoji: '📷'),
  WordItem('Dinner', 'อาหารเย็น', emoji: '🍽️'),
  WordItem('Elephant', 'ช้าง', emoji: '🐘'),
  WordItem('Always', 'เสมอ', emoji: '♾️'),
  WordItem('Answer', 'คำตอบ / ตอบ', emoji: '✅'),
  WordItem('Before', 'ก่อน', emoji: '⏪'),
  WordItem('Because', 'เพราะว่า', emoji: '🤔'),
  WordItem('Clean', 'สะอาด / ทำความสะอาด', emoji: '🧼'),
  WordItem('Cold', 'หนาว', emoji: '❄️'),
  WordItem('Early', 'เร็ว / แต่เช้า', emoji: '🌅'),
  WordItem('Finish', 'เสร็จ / จบ', emoji: '🏁'),
  WordItem('Funny', 'ตลก', emoji: '🤣'),
  WordItem('Happy', 'มีความสุข', emoji: '😊'),
  WordItem('Important', 'สำคัญ', emoji: '⭐'),
  WordItem('Listen', 'ฟัง', emoji: '👂'),
  WordItem('Need', 'ต้องการ', emoji: '🙋‍♂️'),
  WordItem('Noise', 'เสียงดัง', emoji: '🔊'),
  WordItem('Quiet', 'เงียบ', emoji: '🤫'),
  WordItem('Sometimes', 'บางครั้ง', emoji: '🔄'),
  WordItem('Together', 'ด้วยกัน', emoji: '🤝'),
  WordItem('Wait', 'รอ', emoji: '⏳'),
  WordItem('Work', 'ทำงาน', emoji: '💼'),
  WordItem('Afraid', 'กลัว', emoji: '😨'),
  WordItem('Begin', 'เริ่มต้น', emoji: '🚦'),
  WordItem('Carry', 'ถือ / แบก', emoji: '👜'),
  WordItem('Change', 'เปลี่ยน', emoji: '🔁'),
  WordItem('Choose', 'เลือก', emoji: '📝'),
  WordItem('Clothes', 'เสื้อผ้า', emoji: '👗'),
  WordItem('Different', 'แตกต่าง', emoji: '🆚'),
  WordItem('Easy', 'ง่าย', emoji: '👌'),
  WordItem('Family', 'ครอบครัว', emoji: '👨‍👩‍👧‍👦'),
  WordItem('Friend', 'เพื่อน', emoji: '🧑‍🤝‍🧑'),
  WordItem('Help', 'ช่วย', emoji: '🆘'),
  WordItem('Idea', 'ความคิด', emoji: '💡'),
  WordItem('Laugh', 'หัวเราะ', emoji: '😂'),
  WordItem('Learn', 'เรียนรู้', emoji: '📚'),
  WordItem('Meal', 'มื้ออาหาร', emoji: '🍽️'),
  WordItem('Minute', 'นาที', emoji: '⏱️'),
  WordItem('Place', 'สถานที่', emoji: '📍'),
  WordItem('Slow', 'ช้า', emoji: '🐢'),
  WordItem('Strong', 'แข็งแรง', emoji: '💪'),
];

final List<WordItem> hardWords = [
  WordItem('Abandon', 'ละทิ้ง', emoji: '🏃‍♂️'),
  WordItem('Benevolent', 'ใจดีมีเมตตา', emoji: '🤲'),
  WordItem('Complicated', 'ซับซ้อน', emoji: '🧩'),
  WordItem('Determination', 'ความมุ่งมั่น', emoji: '💪'),
  WordItem('Enthusiastic', 'กระตือรือร้น', emoji: '🤩'),
  WordItem('Accumulate', 'สะสม', emoji: '📈'),
  WordItem('Adapt', 'ปรับตัว', emoji: '🔧'),
  WordItem('Advantage', 'ข้อดี', emoji: '🏆'),
  WordItem('Ambition', 'ความทะเยอทะยาน', emoji: '🎯'),
  WordItem('Analyze', 'วิเคราะห์', emoji: '🔎'),
  WordItem('Anxiety', 'ความวิตกกังวล', emoji: '😰'),
  WordItem('Appreciate', 'ซาบซึ้ง / เห็นคุณค่า', emoji: '🙏'),
  WordItem('Assume', 'สมมติ / คิดว่า', emoji: '🤔'),
  WordItem('Benefit', 'ผลประโยชน์', emoji: '💰'),
  WordItem('Capable', 'มีความสามารถ', emoji: '💪'),
  WordItem('Conclusion', 'ข้อสรุป', emoji: '📝'),
  WordItem('Confidence', 'ความมั่นใจ', emoji: '😎'),
  WordItem('Consider', 'พิจารณา', emoji: '🤨'),
  WordItem('Convince', 'โน้มน้าว', emoji: '🗣️'),
  WordItem('Criticize', 'วิจารณ์', emoji: '🧐'),
  WordItem('Decision', 'การตัดสินใจ', emoji: '🎯'),
  WordItem('Decrease', 'ลดลง', emoji: '📉'),
  WordItem('Effective', 'มีประสิทธิภาพ', emoji: '⚙️'),
  WordItem('Emphasize', 'เน้น', emoji: '🔊'),
  WordItem('Encourage', 'สนับสนุน / ให้กำลังใจ', emoji: '👏'),
  WordItem('Environment', 'สิ่งแวดล้อม', emoji: '🌎'),
  WordItem('Establish', 'ก่อตั้ง', emoji: '🏛️'),
  WordItem('Exaggerate', 'พูดเกินจริง', emoji: '🤥'),
  WordItem('Experience', 'ประสบการณ์', emoji: '🎓'),
  WordItem('Familiar', 'คุ้นเคย', emoji: '👀'),
  WordItem('Financial', 'ทางการเงิน', emoji: '💵'),
  WordItem('Flexible', 'ยืดหยุ่น', emoji: '🧘‍♂️'),
  WordItem('Fortunately', 'อย่างโชคดี', emoji: '🍀'),
  WordItem('Generate', 'สร้าง / ผลิต', emoji: '⚡'),
  WordItem('Independent', 'เป็นอิสระ', emoji: '🦅'),
  WordItem('Influence', 'อิทธิพล', emoji: '🌊'),
  WordItem('Inspire', 'สร้างแรงบันดาลใจ', emoji: '✨'),
  WordItem('Intelligent', 'ฉลาด', emoji: '🧠'),
  WordItem('Motivation', 'แรงจูงใจ', emoji: '🔥'),
  WordItem('Neglect', 'ละเลย', emoji: '🙈'),
  WordItem('Opportunity', 'โอกาส', emoji: '🚪'),
  WordItem('Participate', 'เข้าร่วม', emoji: '🙋‍♀️'),
  WordItem('Significant', 'สำคัญ', emoji: '📌'),
];
